### PR TITLE
fix: make acceptance tests working using static fields in tests ancestor

### LINKED ISSUE #207: acceptance test are not working after split
it says - project can't be null

### PR DESCRIPTION
**Pull request by pirkogdc**
closes #207

### CODE REVIEW

File: src/test/java/com/gooddata/AbstractGoodDataAT.java [hunk 1]
```diff
@@ -14,23 +14,36 @@
...
+
+    // tear down project and gd on shutdown
+    // this logic can't be in @After* methods, because we have inter-classes dependent tests
+    static {
+        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
+            @Override
+            public void run() {
+                if (gd != null) {
+                    if (project != null) {
+                        gd.getProjectService().removeProject(project);
```
Comment (pirkogdc) [inline src/test/java/com/gooddata/AbstractGoodDataAT.java]: I know this is ugly, alternatively we can define test group for all project dependent and setup `@AfterGroup` for project removal. However I see no better solution for `gd.logout()` :(

Comment (martiner) [inline src/test/java/com/gooddata/AbstractGoodDataAT.java]: `@AfterSuite`?

Comment (pirkogdc) [inline src/test/java/com/gooddata/AbstractGoodDataAT.java]: you are right - fixed
